# Generated by Django 5.2.2 on 2025-08-22 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_logo', models.ImageField(default='teams/default.png', upload_to='teams/')),
                ('away_team_logo', models.ImageField(default='teams/default.png', upload_to='teams/')),
                ('home_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('away_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('is_olympia_home', models.BooleanField(default=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_address', models.CharField(blank=True, max_length=300)),
                ('maps_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('competition', models.CharField(blank=True, max_length=100)),
                ('match_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('match', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('ticket_type', models.CharField(choices=[('single', 'Entrada Individual'), ('season', 'Abono Temporada')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
