# Generated by Django 5.2.2 on 2025-08-17 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('match', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
