# Generated by Django 5.2.2 on 2025-08-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_match_away_team_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField()),
                ('position', models.CharField(choices=[('portero', 'Portera'), ('defensa', 'Defensa'), ('centrocampista', 'Centrocampista'), ('delantero', 'Delantera'), ('tecnico', 'Cuerpo Técnico')], max_length=20)),
                ('team', models.CharField(choices=[('senior_a', 'Senior A - Primer Equipo'), ('senior_b', 'Senior B'), ('cantera', 'Cantera')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Española', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
