# Generated by Django 5.2.2 on 2025-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, help_text='Número de jornada (ej: 1, 2, 3...)', null=True, verbose_name='Matchday/Jornada'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, help_text="Fase o etapa del torneo (ej: 'Group Stage', 'Quarterfinals', etc.)", max_length=50, verbose_name='Stage/Phase'),
        ),
    ]
