# Generated by Django 5.2.2 on 2025-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('single', 'Entrada Individual'), ('season', 'Abono Temporada')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
