# Generated by Django 5.2.2 on 2025-08-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_match_matchday_match_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, help_text='Número de jornada (ej: 1, 2, 3...)', null=True, verbose_name='Jornada'),
        ),
    ]
