# Generated by Django 5.2.2 on 2025-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_playerregistration_alter_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerregistration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='registration_data',
            field=models.JSONField(default=dict),
        ),
    ]
