# Generated by Django 5.2.2 on 2025-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_playerregistration_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerregistration',
            name='registration_data',
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='equipment_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='previous_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
