# Generated by Django 5.2.2 on 2025-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_playerregistration_registration_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
