# Generated by Django 5.2.2 on 2025-08-30 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_playerregistration_registration_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Prebenjamín', 'Prebenjamín'), ('Benjamín', 'Benjamín'), ('Alevín', 'Alevín'), ('Infantil', 'Infantil'), ('Cadete', 'Cadete'), ('Juvenil', 'Juvenil'), ('Senior', 'Senior')], max_length=20)),
                ('position', models.CharField(choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], max_length=20)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Años de experiencia', null=True)),
                ('previous_clubs', models.CharField(blank=True, max_length=200)),
                ('medical_conditions', models.TextField(blank=True)),
                ('inscription_number', models.CharField(default=uuid.uuid4, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(default='2023/2024', max_length=20)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('included_items', models.TextField(default='[{"item": "Uniforme completo", "quantity": 1}, {"item": "Seguro médico", "quantity": 1}, {"item": "Acceso a instalaciones", "quantity": 1}]')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PlayerRegistration',
        ),
    ]
