# Generated by Django 5.2.2 on 2025-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_inscription_delete_playerregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='inscription_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
