# Generated by Django 5.2.2 on 2025-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_inscription_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
