# Generated by Django 5.2.2 on 2025-08-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_player_display_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
