# Generated by Django 5.2.2 on 2025-08-31 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_player_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
