# Generated by Django 5.2.2 on 2025-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_category',
            field=models.CharField(choices=[('senior_a', 'Senior A - Primer Equipo'), ('senior_b', 'Senior B'), ('cantera', 'Cantera'), ('other', 'Otro')], default='senior_a', max_length=20, verbose_name='Categoría del Equipo'),
        ),
    ]
