# Generated by Django 5.2.2 on 2026-02-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('clothing', 'Ropa'), ('footwear', 'Calzado'), ('merch', 'Merchandising')], max_length=20)),
                ('image', models.ImageField(upload_to='shop/')),
                ('image_hover', models.ImageField(blank=True, help_text='Aparece al hacer hover', upload_to='shop/')),
                ('has_sizes', models.BooleanField(default=False, help_text='¿Tiene tallas?')),
                ('has_colors', models.BooleanField(default=False, help_text='¿Tiene colores?')),
                ('size_list', models.TextField(blank=True, help_text='Tallas separadas por comas. Ej: XS,S,M,L,XL o 36,37,38,39,40')),
                ('color_list', models.TextField(blank=True, help_text='Colores separados por comas. Ej: Azul,Verde,Rojo')),
                ('badge', models.CharField(blank=True, help_text='Ej: NUEVO, OFERTA', max_length=50)),
                ('price_variant', models.CharField(blank=True, help_text='Ej: Diseño delante y detrás', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
